---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/doctors":
    get:
      summary: Retrieves all doctors
      responses:
        '200':
          description: doctors retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    description:
                      type: string
                    avatar:
                      type: string
                    image_url:
                      type: string
                    detail:
                      type: object
                      properties:
                        price:
                          type: integer
                        specialization:
                          type: string
                        studies:
                          type: string
                  required:
                  - id
                  - name
                  - age
                  - description
                  - avatar
                  - image_url
                  - detail
    post:
      summary: Creates a doctor
      parameters: []
      responses:
        '201':
          description: doctor created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                description:
                  type: string
                avatar:
                  type: string
                image_url:
                  type: string
                detail_attributes:
                  type: object
                  properties:
                    price:
                      type: integer
                    specialization:
                      type: string
                    studies:
                      type: string
              required:
              - name
              - age
              - description
              - avatar
              - image_url
              - detail_attributes
  "/doctors/{id}":
    get:
      summary: Retrieves a doctor
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: doctor found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  age:
                    type: integer
                  description:
                    type: string
                  avatar:
                    type: string
                  image_url:
                    type: string
                  detail:
                    type: object
                    properties:
                      price:
                        type: integer
                      specialization:
                        type: string
                      studies:
                        type: string
                required:
                - id
                - name
                - age
                - description
                - avatar
                - image_url
                - detail
        '404':
          description: doctor not found
    delete:
      summary: Deletes a doctor
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: doctor deleted
        '404':
          description: doctor not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:4000/
